name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.buildx-cache
          key: tmp-${{ github.sha }}
          restore-keys: |
            tmp-
            
      - name: Pre-build memory usage
        run: |
          echo "=== Before build ==="
          free -h
          df -h
            
      - name: Install dependencies
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update -y
            sudo apt-get install -y shellcheck bats
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install shellcheck bats
          else
            choco install shellcheck
            # Bats may not exist natively on Windows, skip if unavailable
          fi

      - name: Install ToolGit
        shell: bash
        run: make install

      - name: Run Lint
        shell: bash
        run: make lint

      - name: Run CLI Tests
        shell: bash
        run: make test

      - name: Run Bats Tests
        shell: bash
        run: make test-bats || echo "⚠️ Skipping Bats tests if unsupported on Windows"

      - name: Check no test repos remain
        run: |
          if ls /tmp/git-helpers-test.* 1>/dev/null 2>&1; then
            echo "Error: leftover test repos detected!"
            exit 1
          fi
          
